# Generated by Django 5.2.1 on 2025-06-04 06:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('max_users', models.IntegerField(default=50)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('grid_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('pen', 'Pen'), ('line', 'Line'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('text', 'Text'), ('image', 'Image'), ('eraser', 'Eraser')], max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('stroke_width', models.FloatField(default=2)),
                ('opacity', models.FloatField(default=1.0)),
                ('path_data', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('font_size', models.IntegerField(default=16)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='whiteboard_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('z_index', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='whiteboard.room')),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('elements_data', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='whiteboard.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('draw', 'Draw'), ('edit', 'Edit'), ('admin', 'Admin')], default='draw', max_length=10)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='whiteboard.room')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('cursor_x', models.FloatField(default=0)),
                ('cursor_y', models.FloatField(default=0)),
                ('cursor_color', models.CharField(default='#000000', max_length=7)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='whiteboard.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
